In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Fraud.csv')

In [3]:
df.shape

(6362620, 11)

In [4]:
df.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [5]:
df.tail()

step      type      amount     nameOrig  oldbalanceOrg  \
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
6362615             0.0   C776919290            0.00       339682.13        1   
6362616             0.0  C1881841831            0.00            0.00        1   
6362617             0.0  C1365125890        68488.84      6379898.11        1   
6362618             0.0  C2080388513            0.00            0.00        1   
6362619             0.0   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [7]:
df.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [8]:
#data cleaning 
df.isnull().sum()#Counts of null values in each column

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [9]:
df[df.duplicated()]


Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [10]:
df.drop(columns=['nameOrig','nameDest'],inplace=True)

In [11]:
df.head()

step      type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   PAYMENT   9839.64       170136.0       160296.36             0.0   
1     1   PAYMENT   1864.28        21249.0        19384.72             0.0   
2     1  TRANSFER    181.00          181.0            0.00             0.0   
3     1  CASH_OUT    181.00          181.0            0.00         21182.0   
4     1   PAYMENT  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  
0             0.0        0               0  
1             0.0        0               0  
2             0.0        1               0  
3             0.0        1               0  
4             0.0        0               0

In [12]:
object_List = df.select_dtypes(include = "object").columns
print (object_List)

Index(['type'], dtype='object')


In [13]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['type']=le.fit_transform(df['type'])
df['type']

0          3
1          3
2          4
3          1
4          3
          ..
6362615    1
6362616    4
6362617    1
6362618    4
6362619    1
Name: type, Length: 6362620, dtype: int32

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 9 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            int32  
 2   amount          float64
 3   oldbalanceOrg   float64
 4   newbalanceOrig  float64
 5   oldbalanceDest  float64
 6   newbalanceDest  float64
 7   isFraud         int64  
 8   isFlaggedFraud  int64  
dtypes: float64(5), int32(1), int64(3)
memory usage: 412.6 MB


In [15]:
df

step  type      amount  oldbalanceOrg  newbalanceOrig  \
0           1     3     9839.64      170136.00       160296.36   
1           1     3     1864.28       21249.00        19384.72   
2           1     4      181.00         181.00            0.00   
3           1     1      181.00         181.00            0.00   
4           1     3    11668.14       41554.00        29885.86   
...       ...   ...         ...            ...             ...   
6362615   743     1   339682.13      339682.13            0.00   
6362616   743     4  6311409.28     6311409.28            0.00   
6362617   743     1  6311409.28     6311409.28            0.00   
6362618   743     4   850002.52      850002.52            0.00   
6362619   743     1   850002.52      850002.52            0.00   

         oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                  0.00            0.00        0               0  
1                  0.00            0.00        0               0  
2                  0.00            0.00        1               0  
3              21182.00            0.00        1               0  
4                  0.00            0.00        0               0  
...                 ...             ...      ...             ...  
6362615            0.00       339682.13        1               0  
6362616            0.00            0.00        1               0  
6362617        68488.84      6379898.11        1               0  
6362618            0.00            0.00        1               0  
6362619      6510099.11      7360101.63        1               0  

[6362620 rows x 9 columns]

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import itertools
from collections import Counter
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score

In [17]:
X = df.drop(["isFraud"], axis= 1)
Y = df["isFraud"]

In [18]:
# Spliting the data for training and testing 
(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size= 0.3, random_state= 42)

In [19]:
X_train.shape


(4453834, 8)

In [20]:
X_test.shape

(1908786, 8)

# It takes time for training 

In [21]:
#Logistic Regression

logistic_regression=LogisticRegression()
logistic_regression.fit(X_train, Y_train)

logistic_regression_pred=logistic_regression.predict(X_test)

In [22]:
print("====================Logistic Regression====================")
print('Accuracy Score:-',accuracy_score(Y_test,logistic_regression_pred)*100)
print("-----------------------------------------------------------")
print('Classification Report:-\n',classification_report(Y_test,logistic_regression_pred))
print("-----------------------------------------------------------")
print('Confusion Matrix:-\n',confusion_matrix(Y_test,logistic_regression_pred))
print("-----------------------------------------------------------")
print('ROC AUC Score:-',roc_auc_score(Y_test,logistic_regression_pred))

====================Logistic Regression====================
Accuracy Score:- 99.83261612354659
-----------------------------------------------------------
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.37      0.43      0.40      2435

    accuracy                           1.00   1908786
   macro avg       0.68      0.72      0.70   1908786
weighted avg       1.00      1.00      1.00   1908786

-----------------------------------------------------------
Confusion Matrix:-
 [[1904536    1815]
 [   1380    1055]]
-----------------------------------------------------------
ROC AUC Score:- 0.7161564031803918


In [23]:
#Random Forest Classifier
rfc =  RandomForestClassifier(n_estimators= 100)
rfc.fit(X_train, Y_train)

rfc_pred=rfc.predict(X_test)

In [24]:
print("====================Random Forest Classifier====================")
print('Accuracy Score:-',accuracy_score(Y_test,rfc_pred)*100)
print("----------------------------------------------------------------")
print('Classification Report:-\n',classification_report(Y_test,rfc_pred))
print("----------------------------------------------------------------")
print('Confusion Matrix:-\n',confusion_matrix(Y_test,rfc_pred))
print("----------------------------------------------------------------")
print('ROC AUC Score:-',roc_auc_score(Y_test,rfc_pred))

====================Random Forest Classifier====================
Accuracy Score:- 99.96945702661273
----------------------------------------------------------------
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.98      0.78      0.87      2435

    accuracy                           1.00   1908786
   macro avg       0.99      0.89      0.93   1908786
weighted avg       1.00      1.00      1.00   1908786

----------------------------------------------------------------
Confusion Matrix:-
 [[1906310      41]
 [    542    1893]]
----------------------------------------------------------------
ROC AUC Score:- 0.8886956119744801


In [25]:
#Decision Tree Classifier
decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(X_train, Y_train) 

decision_tree_classifier_pred=decision_tree_classifier.predict(X_test)

In [26]:
print("====================Decision Tree Classifier====================")
print('Accuracy Score:-',accuracy_score(Y_test,decision_tree_classifier_pred)*100)
print("----------------------------------------------------------------")
print('Classification Report:-\n',classification_report(Y_test,decision_tree_classifier_pred))
print("----------------------------------------------------------------")
print('Confusion Matrix:-\n',confusion_matrix(Y_test,decision_tree_classifier_pred))
print("----------------------------------------------------------------")
print('ROC AUC Score:-',roc_auc_score(Y_test,decision_tree_classifier_pred))

====================Decision Tree Classifier====================
Accuracy Score:- 99.97097631688413
----------------------------------------------------------------
Classification Report:-
               precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.90      0.87      0.88      2435

    accuracy                           1.00   1908786
   macro avg       0.95      0.94      0.94   1908786
weighted avg       1.00      1.00      1.00   1908786

----------------------------------------------------------------
Confusion Matrix:-
 [[1906105     246]
 [    308    2127]]
----------------------------------------------------------------
ROC AUC Score:- 0.9366911256456489


# Decision Tree Classifier is the best performing model with a prediction accuracy of approximately 99.9708%.

In [27]:
import warnings
warnings.filterwarnings("ignore")

# 0= Not Fraud
# 1= Fraud

In [28]:
decision_tree_classifier.predict([[1,2,181.64,181.0,181.36,0.0,0.0,0]])

array([0], dtype=int64)

In [29]:
decision_tree_classifier.predict([[743,3,7245287.00,728522.00,123.00,154.00,0.00,0]])

array([1], dtype=int64)

In [30]:
decision_tree_classifier.predict([[719,2,154.00,123.00,123.00,154.00,0.00,0]])

array([1], dtype=int64)